all: test1.o test2.o test3.o test4.o test5.o test6.o
test1.o: test1.c
	gcc -o test1.o test1.c
test2.o: test2.c
	gcc -o test2.o test2.c
test3.o: test3.c
	gcc -o test3.o test3.c
test4.o: test4.c
	gcc -o test4.o test4.c
test5.o: test5.c
	gcc -o test5.o test5.c
test6.o: test6.c
	gcc -o test6.o test6.c

clean:
	rm *.o
